/* Generated by setup.html */

window.profiles = [
  {
    "name": "Guest",
    "image": "./Profiles/Guest.jpg",
    "bgColors": []
  }
];
window._customServerTitle = "Test Library New 6t";

(function setServerTitle(){
  const el = document.getElementById('siteTitle');
  if (!el) return;
  const img = el.querySelector('img');
  const imgHtml = img ? img.outerHTML : '';
  const safeTitle = (typeof window._customServerTitle === 'string' && window._customServerTitle.length)
    ? window._customServerTitle
    : '';
  el.innerHTML = safeTitle + ' ' + imgHtml;
  try { document.title = safeTitle; } catch(e){}
})();
